name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # Atau gunakan branch lain, misalnya master

jobs:
  build:
    runs-on: ubuntu-latest  # Menjalankan di lingkungan Ubuntu terbaru

    steps:
      # Step 1: Checkout code dari GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (diperlukan jika kamu menggunakan npm, misalnya untuk menjalankan build)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Versi Node.js yang digunakan (sesuaikan dengan versi yang diinginkan)

      # Step 3: Install dependensi (jika ada, misalnya package.json dan npm)
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Build project (Jika kamu perlu build aplikasi, misalnya menggunakan bundler seperti Webpack, Parcel, dll)
      - name: Build project
        run: |
          npm run build  # Jika ada perintah build. Kalau hanya HTML, ini bisa dilewati.

      # Step 5: Deploy ke GitHub Pages menggunakan gh-pages
      - name: Deploy to GitHub Pages
        run: |
          npm install gh-pages --save-dev
          npm run deploy   # Menjalankan perintah deploy yang ada di package.json
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Token GitHub untuk autentikasi

  # Optional: Cek apakah HTML valid
  check-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install html-validator-cli
        run: |
          npm install html-validator-cli --save-dev

      - name: Validate HTML
        run: |
          npx html-validator-cli ./index.html  # Sesuaikan dengan nama file HTML utama
